#!/usr/bin/env python3
"""
Create figure summaries based on the filament dynamics tables.

Produces six plots:
  1. Histogram of per-filament maximum robust length with the user-specified lower tail highlighted.
  2. Scatter of maximum robust length versus z-plane count to visualize dot-like tracks.
  3. Arc-length bar plot with 95% CI (from the length-estimate table) per video.
  4. Histogram of XY slice lengths above a configurable cutoff.
  5. Rod-fit quality scatter showing line-fit R2 versus rod-fit RMSE.
  6. Histograms of rod-fit R2 and normalized rod-fit error.

Produces PNG files in the specified output directory (default `output/`).
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import numpy as np
import pandas as pd

mpl_config_dir = Path("output") / ".mplconfig"
mpl_config_dir.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(mpl_config_dir))

import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot filament dynamics diagnostics.")
    parser.add_argument(
        "--summary-csv",
        default="output/filament_dynamics_summary.csv",
        help="Per-filament summary CSV generated by `filament_dynamics_analysis.py`.",
    )
    parser.add_argument(
        "--processed-csv",
        default="output/processed_filaments.csv",
        help="Filtered filaments CSV that excludes rejected tracks.",
    )
    parser.add_argument(
        "--length-csv",
        default="output/filament_length_estimate.csv",
        help="Length estimate table with CI values.",
    )
    parser.add_argument(
        "--xy-slice-csv",
        default="output/filament_xy_slice_measurements.csv",
        help="Per-slice XY filament length measurements.",
    )
    parser.add_argument(
        "--output-dir",
        default="output",
        help="Directory to write the generated figure PNGs.",
    )
    parser.add_argument(
        "--size-tail-quantile",
        type=float,
        default=0.1,
        help="Lower-tail percentile used to mark the histogram cut-off.",
    )
    parser.add_argument(
        "--xy-hist-min-length-um",
        type=float,
        default=0.9,
        help="Minimum XY slice length included in the XY histogram.",
    )
    return parser.parse_args()


def ensure_output_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def plot_size_histogram(summary: pd.DataFrame, quantile: float, path: Path) -> None:
    lengths = summary["max_length_um"].dropna().to_numpy(dtype=float)
    if lengths.size == 0:
        return

    threshold = float(summary["max_length_um"].quantile(float(quantile)))
    mu = float(lengths.mean())
    sigma = float(lengths.std(ddof=0))
    fig, ax = plt.subplots(figsize=(6, 4))
    counts, bins, _ = ax.hist(lengths, bins=30, color="#5B8FF9", edgecolor="black", alpha=0.75)
    if sigma > 0 and bins.size > 1:
        x = np.linspace(float(bins[0]), float(bins[-1]), 400)
        bin_width = float(bins[1] - bins[0])
        pdf = (1.0 / (sigma * np.sqrt(2.0 * np.pi))) * np.exp(-0.5 * ((x - mu) / sigma) ** 2)
        ax.plot(x, pdf * lengths.size * bin_width, color="#262626", linewidth=2.0, label="Gaussian fit")
    ax.axvline(threshold, color="#F46C93", linestyle="--", label=f"{quantile*100:.0f}th %ile")
    ax.set_xlabel("Largest filament length in video (um)")
    ax.set_ylabel("Count")
    ax.set_title("Per-filament maximum length distribution")
    ax.text(
        0.98,
        0.95,
        f"mu = {mu:.2f} um\nsigma = {sigma:.2f} um",
        transform=ax.transAxes,
        ha="right",
        va="top",
        bbox={"boxstyle": "round", "facecolor": "white", "alpha": 0.85, "edgecolor": "#999999"},
    )
    ax.legend()
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def plot_z_plane_vs_size(summary: pd.DataFrame, path: Path) -> None:
    fig, ax = plt.subplots(figsize=(6, 4))
    scatter = ax.scatter(
        summary["max_length_um"],
        summary["max_z_plane_count"],
        c=summary["directionality"],
        cmap="viridis",
        edgecolor="black",
        linewidth=0.5,
    )
    ax.set_xlabel("Largest filament length in video (um)")
    ax.set_ylabel("Distinct z-planes seen")
    ax.set_title("Length vs. z-plane coverage")
    cbar = fig.colorbar(scatter, ax=ax)
    cbar.set_label("Directionality (1 = straight)")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def plot_length_errorbars(length_df: pd.DataFrame, path: Path) -> None:
    if length_df.empty:
        return

    length_df = length_df.sort_values("mean_arc_length_um", ascending=False)
    fig, ax = plt.subplots(figsize=(7, 4))
    indices = range(len(length_df))
    ax.bar(
        indices,
        length_df["mean_arc_length_um"],
        yerr=length_df["ci95"],
        color="#7CB305",
        capsize=4,
    )
    ax.set_ylabel("Mean arc length (um)")
    ax.set_xlabel("Video index")
    ax.set_title("Mean filament arc length per video (with 95% CI)")
    ax.set_xticks(indices)
    ax.set_xticklabels([str(i + 1) for i in indices])
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def plot_xy_slice_histogram(xy_slice_df: pd.DataFrame, min_length_um: float, path: Path) -> None:
    if xy_slice_df.empty:
        return

    plot_df = xy_slice_df.loc[xy_slice_df["xy_length_um"] >= float(min_length_um)].copy()
    if plot_df.empty:
        return

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.hist(plot_df["xy_length_um"], bins=30, color="#FA8C16", edgecolor="black")
    ax.axvline(float(min_length_um), color="#262626", linestyle="--", label=f">= {min_length_um:.2f} um")
    ax.set_xlabel("XY slice filament length (um)")
    ax.set_ylabel("Count")
    ax.set_title("XY slice lengths above threshold")
    ax.legend()
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def plot_rod_fit_quality(summary: pd.DataFrame, path: Path) -> None:
    required = {"mean_linearity_r2", "mean_rod_fit_rmse_um", "max_length_um", "rotation_angle_deg"}
    if summary.empty or not required.issubset(summary.columns):
        return

    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    scatter = ax.scatter(
        summary["mean_linearity_r2"],
        summary["mean_rod_fit_rmse_um"],
        c=summary["rotation_angle_deg"],
        s=20 + 10 * summary["max_length_um"].clip(lower=0.0),
        cmap="plasma",
        edgecolor="black",
        linewidth=0.4,
        alpha=0.85,
    )
    ax.set_xlabel("Mean line-fit R2")
    ax.set_ylabel("Mean rod-fit RMSE (um)")
    ax.set_title("Rod-fit quality per filament")
    cbar = fig.colorbar(scatter, ax=ax)
    cbar.set_label("Rotation angle (deg)")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def plot_rod_fit_distributions(summary: pd.DataFrame, path: Path) -> None:
    required = {"mean_linearity_r2", "mean_rod_fit_cv"}
    if summary.empty or not required.issubset(summary.columns):
        return

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))

    axes[0].hist(summary["mean_linearity_r2"], bins=20, color="#4C6EF5", edgecolor="black", alpha=0.8)
    axes[0].axvline(float(summary["mean_linearity_r2"].median()), color="#111111", linestyle="--", label="median")
    axes[0].set_xlabel("Mean line-fit R2")
    axes[0].set_ylabel("Count")
    axes[0].set_title("Rod-likeness")
    axes[0].legend()

    axes[1].hist(summary["mean_rod_fit_cv"], bins=20, color="#12B886", edgecolor="black", alpha=0.8)
    axes[1].axvline(float(summary["mean_rod_fit_cv"].median()), color="#111111", linestyle="--", label="median")
    axes[1].set_xlabel("Mean rod-fit CV")
    axes[1].set_ylabel("Count")
    axes[1].set_title("Normalized rod-fit error")
    axes[1].legend()

    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def run_plot(
    summary_csv: Path,
    processed_csv: Path | None,
    length_csv: Path,
    xy_slice_csv: Path | None,
    output_dir: Path,
    size_tail_quantile: float,
    xy_hist_min_length_um: float,
) -> None:
    ensure_output_dir(output_dir)
    summary = pd.read_csv(summary_csv)
    length_df = pd.read_csv(length_csv) if length_csv.exists() else pd.DataFrame()
    xy_slice_df = pd.read_csv(xy_slice_csv) if xy_slice_csv and xy_slice_csv.exists() else pd.DataFrame()
    filtered = None
    if processed_csv and processed_csv.exists():
        filtered = pd.read_csv(processed_csv)
    hist_path = output_dir / "filament_length_hist.png"
    scatter_path = output_dir / "mean_length_vs_z_planes.png"
    bars_path = output_dir / "arc_length_ci.png"
    xy_hist_path = output_dir / "xy_slice_length_hist.png"
    rod_fit_path = output_dir / "rod_fit_quality.png"
    rod_fit_dist_path = output_dir / "rod_fit_distributions.png"
    plot_df = filtered if filtered is not None and not filtered.empty else summary
    plot_size_histogram(plot_df, size_tail_quantile, hist_path)
    plot_z_plane_vs_size(plot_df, scatter_path)
    plot_length_errorbars(length_df, bars_path)
    plot_xy_slice_histogram(xy_slice_df, xy_hist_min_length_um, xy_hist_path)
    plot_rod_fit_quality(plot_df, rod_fit_path)
    plot_rod_fit_distributions(plot_df, rod_fit_dist_path)
    print(f"Plots saved to {output_dir}")


def main() -> None:
    args = parse_args()
    run_plot(
        Path(args.summary_csv),
        Path(args.processed_csv),
        Path(args.length_csv),
        Path(args.xy_slice_csv),
        Path(args.output_dir),
        args.size_tail_quantile,
        args.xy_hist_min_length_um,
    )


if __name__ == "__main__":
    main()
