#!/usr/bin/env python3
"""
Filament 3D Path Viewer — Interactive Trajectory Visualization

Features:
- Load tracking CSVs (frame, filament_id, z, y, x)
- Interactive 3D Plotly visualization of filament paths
- Select individual filaments or show all
- Color-coded paths by frame number (temporal progression)
"""

import os
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import gradio as gr
import glob

def get_results_files():
    files = glob.glob("results/*_tracking.csv")
    return sorted(files)

def load_csv_data(file_path):
    if not file_path or not os.path.exists(file_path):
        return None, "File not found."
    try:
        df = pd.read_csv(file_path)
        required_cols = {'frame', 'filament_id', 'z', 'y', 'x'}
        if not required_cols.issubset(df.columns):
            return None, f"CSV missing required columns: {required_cols - set(df.columns)}"
        return df, f"Successfully loaded {len(df)} points from {os.path.basename(file_path)}."
    except Exception as e:
        return None, f"Error loading CSV: {str(e)}"

def generate_3d_path_plot(df, selected_fids, show_all=False):
    if df is None or df.empty:
        return go.Figure()

    fig = go.Figure()
    
    if show_all:
        fids = df['filament_id'].unique()
    else:
        # selected_fids might be strings like "Filament 1", extract the int
        fids = []
        for s in selected_fids:
            try:
                fids.append(int(s.replace("Filament ", "")))
            except:
                pass
    
    if not fids:
        # Show a placeholder
        fig.add_trace(go.Scatter3d(x=[0], y=[0], z=[0], mode='markers', marker=dict(opacity=0), name="No filaments selected"))
    else:
        for fid in fids:
            sub = df[df['filament_id'] == fid].sort_values('frame')
            if sub.empty: continue
            
            # Create a path with gradient color based on frame
            fig.add_trace(go.Scatter3d(
                x=sub['x'], y=sub['y'], z=sub['z'],
                mode='lines+markers',
                marker=dict(
                    size=4,
                    color=sub['frame'],
                    colorscale='Viridis',
                    showscale=(fid == fids[0]), # Only show colorbar for first one to avoid clutter
                    colorbar=dict(title="Frame") if (fid == fids[0]) else None
                ),
                line=dict(width=3),
                name=f"Filament {fid}"
            ))

    # Calculate aspect ratio based on data range to avoid squashing
    xr = df['x'].max() - df['x'].min()
    yr = df['y'].max() - df['y'].min()
    zr = df['z'].max() - df['z'].min()
    
    # We want to maintain relative physical scale, but Z is sparse so we might stretch it a bit
    # Standard pixels are roughly isotropic in XY, Z is slightly different but usually 
    # we want to see it clearly.
    
    fig.update_layout(
        scene=dict(
            xaxis_title='X (px)',
            yaxis_title='Y (px)',
            zaxis_title='Z (slices)',
            aspectmode='data' # This keeps the physical scale relationship
        ),
        margin=dict(l=0, r=0, b=0, t=30),
        title=f"3D Filament Trajectories",
        template="plotly_dark",
        legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
    )
    
    return fig

# Gradio Interface
def update_ui(file_path):
    df, msg = load_csv_data(file_path)
    if df is None:
        return gr.update(choices=[], value=[]), msg, go.Figure()
    
    fids = sorted(df['filament_id'].unique())
    choices = [f"Filament {fid}" for fid in fids]
    
    # Generate initial plot with all filaments
    fig = generate_3d_path_plot(df, [], show_all=True)
    
    return gr.update(choices=choices, value=choices[:1]), msg, fig

def update_plot(file_path, selected_fids, show_all):
    df, _ = load_csv_data(file_path)
    return generate_3d_path_plot(df, selected_fids, show_all)

CSS = """
.gradio-container { max-width: 1200px !important; margin: auto !important; }
h1 { text-align: center; color: #4a90e2; }
"""

with gr.Blocks(theme=gr.themes.Soft(), css=CSS) as demo:
    gr.Markdown("# 🧶 Filament 3D Path Viewer")
    gr.Markdown("Visualize 3D trajectories from tracking CSV files generated by `batch_3d_tracker.py`.")
    
    with gr.Row():
        with gr.Column(scale=1):
            file_input = gr.Dropdown(label="Select Result CSV", choices=get_results_files())
            refresh_files = gr.Button("🔄 Refresh File List")
            
            with gr.Group():
                fid_dropdown = gr.CheckboxGroup(label="Select Filament IDs", choices=[])
                show_all_cb = gr.Checkbox(label="Show All Filaments", value=False)
            
            status_msg = gr.Markdown("Select a file to begin.")
            
        with gr.Column(scale=3):
            plot_3d = gr.Plot(label="Interactive 3D Path")
            
    # Events
    refresh_files.click(lambda: gr.update(choices=get_results_files()), outputs=file_input)
    
    file_input.change(update_ui, inputs=[file_input], outputs=[fid_dropdown, status_msg, plot_3d])
    
    # Plot updates
    fid_dropdown.change(update_plot, inputs=[file_input, fid_dropdown, show_all_cb], outputs=plot_3d)
    show_all_cb.change(update_plot, inputs=[file_input, fid_dropdown, show_all_cb], outputs=plot_3d)

if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", share=True)
