#!/usr/bin/env python3
"""
Create figure summaries based on the filament dynamics tables.

Produces three plots:
  1. Histogram of per-filament mean robust length with the user-specified lower tail highlighted.
  2. Scatter of mean robust length versus z-plane count to visualize dot-like tracks.
  3. Arc-length bar plot with 95% CI (from the length-estimate table) per video.

Produces PNG files in the specified output directory (default `output/`).
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import pandas as pd

mpl_config_dir = Path("output") / ".mplconfig"
mpl_config_dir.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(mpl_config_dir))

import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot filament dynamics diagnostics.")
    parser.add_argument(
        "--summary-csv",
        default="output/filament_dynamics_summary.csv",
        help="Per-filament summary CSV generated by `filament_dynamics_analysis.py`.",
    )
    parser.add_argument(
        "--processed-csv",
        default="output/processed_filaments.csv",
        help="Filtered filaments CSV that excludes rejected tracks.",
    )
    parser.add_argument(
        "--length-csv",
        default="output/filament_length_estimate.csv",
        help="Length estimate table with CI values.",
    )
    parser.add_argument(
        "--output-dir",
        default="output",
        help="Directory to write the generated figure PNGs.",
    )
    parser.add_argument(
        "--size-tail-quantile",
        type=float,
        default=0.1,
        help="Lower-tail percentile used to mark the histogram cut-off.",
    )
    return parser.parse_args()


def ensure_output_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def plot_size_histogram(summary: pd.DataFrame, quantile: float, path: Path) -> None:
    threshold = float(summary["mean_length_um"].quantile(float(quantile)))
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.hist(summary["mean_length_um"], bins=30, color="#5B8FF9", edgecolor="black")
    ax.axvline(threshold, color="#F46C93", linestyle="--", label=f"{quantile*100:.0f}th %ile")
    ax.set_xlabel("Mean filament length (um)")
    ax.set_ylabel("Count")
    ax.set_title("Filament length distribution")
    ax.legend()
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def plot_z_plane_vs_size(summary: pd.DataFrame, path: Path) -> None:
    fig, ax = plt.subplots(figsize=(6, 4))
    scatter = ax.scatter(
        summary["mean_length_um"],
        summary["max_z_plane_count"],
        c=summary["directionality"],
        cmap="viridis",
        edgecolor="black",
        linewidth=0.5,
    )
    ax.set_xlabel("Mean filament length (um)")
    ax.set_ylabel("Distinct z-planes seen")
    ax.set_title("Length vs. z-plane coverage")
    cbar = fig.colorbar(scatter, ax=ax)
    cbar.set_label("Directionality (1 = straight)")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def plot_length_errorbars(length_df: pd.DataFrame, path: Path) -> None:
    if length_df.empty:
        return

    length_df = length_df.sort_values("mean_arc_length_um", ascending=False)
    fig, ax = plt.subplots(figsize=(7, 4))
    indices = range(len(length_df))
    ax.bar(
        indices,
        length_df["mean_arc_length_um"],
        yerr=length_df["ci95"],
        color="#7CB305",
        capsize=4,
    )
    ax.set_ylabel("Mean arc length (um)")
    ax.set_xlabel("Video index")
    ax.set_title("Mean filament arc length per video (with 95% CI)")
    ax.set_xticks(indices)
    ax.set_xticklabels([str(i + 1) for i in indices])
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def run_plot(
    summary_csv: Path,
    processed_csv: Path | None,
    length_csv: Path,
    output_dir: Path,
    size_tail_quantile: float,
) -> None:
    ensure_output_dir(output_dir)
    summary = pd.read_csv(summary_csv)
    length_df = pd.read_csv(length_csv) if length_csv.exists() else pd.DataFrame()
    filtered = None
    if processed_csv and processed_csv.exists():
        filtered = pd.read_csv(processed_csv)
    hist_path = output_dir / "filament_length_hist.png"
    scatter_path = output_dir / "mean_length_vs_z_planes.png"
    bars_path = output_dir / "arc_length_ci.png"
    plot_df = filtered if filtered is not None and not filtered.empty else summary
    plot_size_histogram(plot_df, size_tail_quantile, hist_path)
    plot_z_plane_vs_size(plot_df, scatter_path)
    plot_length_errorbars(length_df, bars_path)
    print(f"Plots saved to {output_dir}")


def main() -> None:
    args = parse_args()
    run_plot(
        Path(args.summary_csv),
        Path(args.processed_csv),
        Path(args.length_csv),
        Path(args.output_dir),
        args.size_tail_quantile,
    )


if __name__ == "__main__":
    main()
